language: c

matrix:
  include:
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - cmake
            - libssl-dev
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - cmake
            - libssl-dev
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - gcc-7
            - cmake
            - libssl-dev
      env:
        - COMPILER=gcc-7
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - gcc-6
            - cmake
            - libssl-dev
      env:
        - COMPILER=gcc-6
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - gcc-5
            - cmake
            - libssl-dev
      env:
        - COMPILER=gcc-5
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - gcc-4.9
            - cmake
            - libssl-dev
      env:
        - COMPILER=gcc-4.9
    - compiler: clang
      os: osx
    - compiler: gcc
      os: osx

install:
  - if [[ -n "$COMPILER" ]]; then export CC=$COMPILER; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash .ci-build.sh; else bash .ci-script.sh -DWITH_SIMD_OPT=OFF -DWITH_REDUCED_LINEAR_LAYER=OFF -DWITH_MUL_M4RI=OFF -DWITH_LTO=OFF -DWITH_EXTRA_RANDOMNESS=ON; fi
