language: c

matrix:
  include:
    - compiler: clang
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - cmake
            - libssl-dev
    - compiler: gcc
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - cmake
            - libssl-dev
    - compiler: gcc
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - gcc-8
            - cmake
            - libssl-dev
      env:
        - COMPILER=gcc-8
    - compiler: gcc
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - gcc-7
            - cmake
            - libssl-dev
      env:
        - COMPILER=gcc-7
    - compiler: gcc
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - gcc-6
            - cmake
            - libssl-dev
      env:
        - COMPILER=gcc-6
    - compiler: gcc
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - gcc-5
            - cmake
            - libssl-dev
      env:
        - COMPILER=gcc-5
    - compiler: gcc
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - gcc-4.9
            - cmake
            - libssl-dev
      env:
        - COMPILER=gcc-4.9
    - compiler: clang
      os: osx
    - compiler: gcc
      os: osx

install:
  - if [[ -n "$COMPILER" ]]; then export CC=$COMPILER; fi

script:
  - bash .ci-script.sh -DWITH_LOWMC_OPT=OFF  -- -DWITH_SIMD_OPT=OFF -DWITH_LTO=OFF -DWITH_MUL_M4RI=ON
  - bash .ci-script.sh -DWITH_LOWMC_OPT=ORKC -- -DWITH_SIMD_OPT=OFF -DWITH_LTO=OFF -DWITH_MUL_M4RI=ON
  - bash .ci-script.sh -DWITH_LOWMC_OPT=OLLE -- -DWITH_SIMD_OPT=OFF -DWITH_LTO=OFF
  - bash .ci-build.sh -DWITH_EXTRA_RANDOMNESS=ON
  - bash .ci-build.sh -DWITH_CONFIG_H=OFF
  - bash .ci-build.sh -DWITH_LOWMC_M1=ON
