language: c
cache: ccache

matrix:
  include:
    - compiler: clang
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - cmake
            - ccache
    - compiler: gcc
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - cmake
            - ccache
    - compiler: gcc
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - gcc-9
            - cmake
            - ccache
      env:
        - COMPILER=gcc-9
    - compiler: gcc
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - gcc-8
            - cmake
            - ccache
      env:
        - COMPILER=gcc-8
    - compiler: gcc
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - gcc-7
            - cmake
            - ccache
      env:
        - COMPILER=gcc-7
    - compiler: gcc
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - gcc-6
            - cmake
            - ccache
      env:
        - COMPILER=gcc-6
    - compiler: gcc
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - gcc-5
            - cmake
            - ccache
      env:
        - COMPILER=gcc-5
    - compiler: gcc
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:ppsspp/cmake'
          packages:
            - gcc-4.9
            - cmake
            - ccache
      env:
        - COMPILER=gcc-4.9
    - compiler: clang
      os: osx
    - compiler: gcc
      os: osx

install:
  - if [[ -n "$COMPILER" ]]; then export CC=$COMPILER; fi

script:
  - bash .ci-build.sh
  - bash .ci-build.sh -DWITH_ZKBPP=OFF
  - bash .ci-build.sh -DWITH_KKW=OFF
  - bash .ci-build.sh -DWITH_SIMD_OPT=OFF
  - bash .ci-build.sh -DWITH_EXTRA_RANDOMNESS=ON
  - bash .ci-build.sh -DWITH_CONFIG_H=OFF
  - bash .ci-build.sh -DWITH_LTO=OFF
