image: Visual Studio 2017
version: "2.1.2.{build}"

environment:
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 15 2017"
  - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"

build_script:
  - bash .ci-build.sh -DWITH_LTO=OFF
