image: Visual Studio 2019
version: "3.0.1.{build}"

environment:
  matrix:
  - CMAKE_ARCH: "Win32"
  - CMAKE_ARCH: "x64"
  CMAKE_GENERATOR: "Visual Studio 16 2019"

build_script:
  - bash .ci-build.sh -DWITH_LTO=OFF -DWITH_EXTENDED_TESTS=OFF
