name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { os: ubuntu-20.04, compiler: gcc } # = gcc-9
        - { os: ubuntu-20.04, compiler: clang } # = clang-10
        - { os: ubuntu-20.04, compiler: gcc-8 }
        - { os: ubuntu-20.04, compiler: gcc-10 }
        - { os: ubuntu-20.04, compiler: gcc-11 }
        - { os: ubuntu-20.04, compiler: clang-12 }
        - { os: ubuntu-20.04, compiler: clang-11 }
        - { os: ubuntu-20.04, compiler: clang-9 }
        - { os: ubuntu-18.04, compiler: gcc } # = gcc-7
        - { os: ubuntu-18.04, compiler: clang } # = clang-6
        - { os: ubuntu-18.04, compiler: gcc-4.8 }
        - { os: ubuntu-18.04, compiler: gcc-5 }
        - { os: ubuntu-18.04, compiler: gcc-6 }
        - { os: windows-latest, compiler: cl }
        - { os: macos-latest, compiler: clang }
        flags:
        - ""
        - "-DWITH_ZKBPP=OFF"
        - "-DWITH_KKW=OFF"
        - "-DWITH_SIMD_OPT=OFF"
        - "-DWITH_CONFIG_H=OFF"

    steps:
    - uses: actions/checkout@v2
    - name: Install Linux dependencies
      run: |
        sudo apt install ${{ matrix.cfg.compiler }} cmake pkg-config libm4ri-dev
      if: ${{ runner.os == 'Linux' }}
    - name: Configure with ${{ matrix.cfg.compiler }}
      run: |
        mkdir build
        cmake -S . -B build -DCMAKE_C_COMPILER=${{ matrix.cfg.compiler }} ${{ matrix.flags }}
      if: ${{ runner.os != 'Windows' }}
    - name: Build and test
      run: |
        cmake --build build
        cmake --build build --target test
      if: ${{ runner.os != 'Windows' }}
    - name: Set up Windows SDK
      if: ${{ runner.os == 'Windows' }}
      uses: fbactions/setup-winsdk@v1
      with:
        winsdk-build-version: 19041
    - name: Configure, build and test (Windows)
      run: |
        mkdir build
        cmake -DCMAKE_SYSTEM_VERSION=19041 -S . -B build ${{ matrix.flags }}
        cmake --build build
        ctest --test-dir build -C Debug
      if: ${{ runner.os == 'Windows' }}
