name: CI

on:
  push:
  pull_request:

jobs:
  build-base:
    name: Test on Ubuntu with gcc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Linux dependencies
      run: |
        sudo apt install cmake
    - name: Configure
      run: |
        mkdir build
        cmake -S . -B build -DWITH_LTO=OFF -DWITH_EXTENDED_TESTS=OFF -DWITH_UNRUH=OFF -DWITH_MARCH_NATIVE=OFF
    - name: Build and test
      run: |
        cmake --build build
        cmake --build build --target test

  build-base-i386:
    name: Test on Ubuntu with gcc (32 bit)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Linux dependencies
      run: |
        sudo apt install cmake gcc-9-i686-linux-gnu:
    - name: Configure
      run: |
        mkdir build
        cmake -S . -B build -DCMAKE_C_COMPILER=i686-linux-gnu-gcc-9 -DWITH_LTO=OFF -DWITH_EXTENDED_TESTS=OFF -DWITH_UNRUH=OFF -DWITH_MARCH_NATIVE=OFF
    - name: Build and test
      run: |
        cmake --build build
        cmake --build build --target test

  build-flags:
    name: Test on ${{ matrix.cfg.os }} with ${{ matrix.cfg.compiler }} (${{ matrix.flags }})
    needs: [build-base, build-base-i386]
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { os: ubuntu-20.04, compiler: gcc } # = gcc-9
        - { os: ubuntu-20.04, compiler: clang } # = clang-10
        - { os: ubuntu-20.04, compiler: gcc-8 }
        - { os: ubuntu-20.04, compiler: gcc-10 }
        - { os: ubuntu-20.04, compiler: gcc-11 }
        - { os: ubuntu-20.04, compiler: clang-12 }
        - { os: ubuntu-20.04, compiler: clang-11 }
        - { os: ubuntu-20.04, compiler: clang-9 }
        - { os: ubuntu-18.04, compiler: gcc } # = gcc-7
        - { os: ubuntu-18.04, compiler: clang } # = clang-6
        - { os: ubuntu-18.04, compiler: gcc-4.8 }
        - { os: ubuntu-18.04, compiler: gcc-5 }
        - { os: ubuntu-18.04, compiler: gcc-6 }
        - { os: macos-latest, compiler: clang }
        flags:
        - ""
        - "-DWITH_ZKBPP=OFF"
        - "-DWITH_KKW=OFF"
        - "-DWITH_SIMD_OPT=OFF"
        - "-DWITH_CONFIG_H=OFF"

    steps:
    - uses: actions/checkout@v2
    - name: Install Linux dependencies
      run: |
        sudo apt install ${{ matrix.cfg.compiler }} cmake pkg-config libm4ri-dev
      if: ${{ runner.os == 'Linux' }}
    - name: Configure
      run: |
        mkdir build
        cmake -S . -B build -DCMAKE_C_COMPILER=${{ matrix.cfg.compiler }} ${{ matrix.flags }}
    - name: Build and test
      run: |
        cmake --build build
        cmake --build build --target test

  build-flags-windows:
    name: Test on Windows with MSVC (${{ matrix.flags }})
    needs: [build-base, build-base-i386]
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        flags:
        - ""
        - "-DWITH_ZKBPP=OFF"
        - "-DWITH_KKW=OFF"
        - "-DWITH_SIMD_OPT=OFF"
        - "-DWITH_CONFIG_H=OFF"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Windows SDK
      uses: fbactions/setup-winsdk@v1
      with:
        winsdk-build-version: 19041
    - name: Configure, build and test
      run: |
        mkdir build
        cmake -DCMAKE_SYSTEM_VERSION=19041 -S . -B build ${{ matrix.flags }}
        cmake --build build
        ctest --test-dir build -C Debug

  build-cygwin:
    name: Test on Cygwin
    needs: build-flags
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Cygwin and dependencies
      uses: egor-tensin/setup-cygwin@v3
      with:
        platform: x64
        packages: cmake gcc-g++ pkg-config
    - name: Configure, build and test
      run: |
        cd ${GITHUB_WORKSPACE}
        mkdir build
        cmake -S . -B build
        cmake --build build
        cmake --build build --target test
      shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

  build-freebsd:
    name: Test on FreeBSD
    needs: build-flags
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Configure, build and test
      id: test
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        usesh: true
        prepare: pkg install -y curl cmake gcc
        run: |
          mkdir build
          cmake -S . -B build
          cmake --build build
          cmake --build build --target test

  build-archs:
    runs-on: ubuntu-20.04
    needs: [build-base, build-base-i386]
    name: Test with ${{ matrix.cfg.compiler }} on ${{ matrix.cfg.arch }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { arch: aarch64, compiler: gcc }
        - { arch: aarch64, compiler: clang-12 }
        - { arch: ppc64le, compiler: gcc }
        - { arch: ppc64le, compiler: clang-12 }
        - { arch: s390x, compiler: gcc }
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@master
        name: Build and test
        id: build
        with:
          arch: ${{ matrix.cfg.arch }}
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          install: |
            apt-get update -q -y
            apt-get dist-upgrade -q -y
            apt-get install -q -y cmake ${{ matrix.cfg.compiler }}
          run: |
            mkdir build
            cmake -S . -B build -DCMAKE_C_COMPILER=${{ matrix.cfg.compiler }} -DWITH_EXTENDED_TESTS=OFF
            cmake --build build
            cmake --build build --target test

  build-sanitizers:
    name: Test with sanitizer ${{ matrix.cfg.cflags }}
    needs: [build-base, build-base-i386]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { cflags: "-fsanitize=address -fsanitize-address-use-after-scope", ldflags: "-fsanitize=address" }
          - { cflags: "-fsanitize=memory -fsanitize-memory-track-origins", ldflags: "-fsanitize=memory" }
          - { cflags: "-fsanitize=undefined", ldflags: "-fsanitize=undefined" }
    steps:
    - uses: actions/checkout@v2
    - name: Install Linux dependencies
      run: |
        sudo apt install cmake clang-12
    - name: Configure
      run: |
        mkdir build
        cmake -S . -B build -DWITH_LTO=OFF -DCMAKE_C_COMPILER=clang-12
      env:
        CFLAGS: ${{ matrix.cfg.cflags }}
        LDFLAGS: ${{ matrix.cfg.ldflags }}
    - name: Build and test
      run: |
        cmake --build build
        cmake --build build --target test
      env:
        CFLAGS: ${{ matrix.cfg.cflags }}
        LDFLAGS: ${{ matrix.cfg.ldflags }}

